# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

rcpp_error_pred_seg_VAR1 <- function(X_futu, X_curr, s, e, lambda, delta, eps) {
    .Call('_changepoints_rcpp_error_pred_seg_VAR1', PACKAGE = 'changepoints', X_futu, X_curr, s, e, lambda, delta, eps)
}

rcpp_DP_VAR1 <- function(X_futu, X_curr, gamma, lambda, delta, eps) {
    .Call('_changepoints_rcpp_DP_VAR1', PACKAGE = 'changepoints', X_futu, X_curr, gamma, lambda, delta, eps)
}

rcpp_DP_poly <- function(y, r, gamma, delta) {
    .Call('_changepoints_rcpp_DP_poly', PACKAGE = 'changepoints', y, r, gamma, delta)
}

rcpp_error_pred_seg_regression <- function(y, X, s, e, lambda, delta, eps) {
    .Call('_changepoints_rcpp_error_pred_seg_regression', PACKAGE = 'changepoints', y, X, s, e, lambda, delta, eps)
}

rcpp_DP_regression <- function(y, X, gamma, lambda, delta, eps) {
    .Call('_changepoints_rcpp_DP_regression', PACKAGE = 'changepoints', y, X, gamma, lambda, delta, eps)
}

rcpp_DP_univar <- function(y, gamma, delta) {
    .Call('_changepoints_rcpp_DP_univar', PACKAGE = 'changepoints', y, gamma, delta)
}

rcpp_basis_poly <- function(n, s, e, r) {
    .Call('_changepoints_rcpp_basis_poly', PACKAGE = 'changepoints', n, s, e, r)
}

dmvnrm_arma_fast <- function(x, mean, sigma) {
    .Call('_changepoints_dmvnrm_arma_fast', PACKAGE = 'changepoints', x, mean, sigma)
}

rcpp_dmvnorm_mixt <- function(evalpoints, mus, sigmas, props) {
    .Call('_changepoints_rcpp_dmvnorm_mixt', PACKAGE = 'changepoints', evalpoints, mus, sigmas, props)
}

rcpp_huber_mean <- function(x, tau) {
    .Call('_changepoints_rcpp_huber_mean', PACKAGE = 'changepoints', x, tau)
}

rcpp_soft_threshold_scalar <- function(x, lambda) {
    .Call('_changepoints_rcpp_soft_threshold_scalar', PACKAGE = 'changepoints', x, lambda)
}

rcpp_lasso_standardized_obj <- function(Xtilde, Ytilde, beta, lambda) {
    .Call('_changepoints_rcpp_lasso_standardized_obj', PACKAGE = 'changepoints', Xtilde, Ytilde, beta, lambda)
}

rcpp_lasso_standardized <- function(Xtilde, Ytilde, beta_start, lambda, eps) {
    .Call('_changepoints_rcpp_lasso_standardized', PACKAGE = 'changepoints', Xtilde, Ytilde, beta_start, lambda, eps)
}

rcpp_lasso_standardized_seq <- function(Xtilde, Ytilde, lambda_seq, eps) {
    .Call('_changepoints_rcpp_lasso_standardized_seq', PACKAGE = 'changepoints', Xtilde, Ytilde, lambda_seq, eps)
}

rcpp_standardizeXY <- function(X, Y) {
    .Call('_changepoints_rcpp_standardizeXY', PACKAGE = 'changepoints', X, Y)
}

rcpp_lasso_seq <- function(X, Y, lambda_seq, eps) {
    .Call('_changepoints_rcpp_lasso_seq', PACKAGE = 'changepoints', X, Y, lambda_seq, eps)
}

rcpp_lassoDPDU_standardized_obj <- function(Mtilde, Vtilde, beta, n, lambda) {
    .Call('_changepoints_rcpp_lassoDPDU_standardized_obj', PACKAGE = 'changepoints', Mtilde, Vtilde, beta, n, lambda)
}

rcpp_lassoDPDU_standardized <- function(Mtilde, Vtilde, beta_start, n, lambda, eps) {
    .Call('_changepoints_rcpp_lassoDPDU_standardized', PACKAGE = 'changepoints', Mtilde, Vtilde, beta_start, n, lambda, eps)
}

rcpp_lassoDPDU_standardized_seq <- function(Mtilde, Vtilde, n, lambda_seq, eps) {
    .Call('_changepoints_rcpp_lassoDPDU_standardized_seq', PACKAGE = 'changepoints', Mtilde, Vtilde, n, lambda_seq, eps)
}

rcpp_lassoDPDU <- function(Mtilde, Vtilde, Xmeans, Ymean, weights, beta_start, n, lambda, eps) {
    .Call('_changepoints_rcpp_lassoDPDU', PACKAGE = 'changepoints', Mtilde, Vtilde, Xmeans, Ymean, weights, beta_start, n, lambda, eps)
}

rcpp_DPDU_regression <- function(y, X, lambda, zeta, eps) {
    .Call('_changepoints_rcpp_DPDU_regression', PACKAGE = 'changepoints', y, X, lambda, zeta, eps)
}

rcpp_lassoDPDU_error <- function(y, X, beta_hat) {
    .Call('_changepoints_rcpp_lassoDPDU_error', PACKAGE = 'changepoints', y, X, beta_hat)
}

rcpp_DPDU2_regression <- function(y, X, lambda, zeta, eps) {
    .Call('_changepoints_rcpp_DPDU2_regression', PACKAGE = 'changepoints', y, X, lambda, zeta, eps)
}

epanker <- function(x, mean, bw) {
    .Call('_changepoints_epanker', PACKAGE = 'changepoints', x, mean, bw)
}

rcpp_epanker_mixt <- function(evalpoints, mus, bw, props) {
    .Call('_changepoints_rcpp_epanker_mixt', PACKAGE = 'changepoints', evalpoints, mus, bw, props)
}

biweiker <- function(x, mean, bw) {
    .Call('_changepoints_biweiker', PACKAGE = 'changepoints', x, mean, bw)
}

rcpp_biweiker_mixt <- function(evalpoints, mus, bw, props) {
    .Call('_changepoints_rcpp_biweiker_mixt', PACKAGE = 'changepoints', evalpoints, mus, bw, props)
}

triweiker <- function(x, mean, bw) {
    .Call('_changepoints_triweiker', PACKAGE = 'changepoints', x, mean, bw)
}

rcpp_triweiker_mixt <- function(evalpoints, mus, bw, props) {
    .Call('_changepoints_rcpp_triweiker_mixt', PACKAGE = 'changepoints', evalpoints, mus, bw, props)
}

rcpp_soft_threshold <- function(x_mat, lambda) {
    .Call('_changepoints_rcpp_soft_threshold', PACKAGE = 'changepoints', x_mat, lambda)
}

rcpp_soft_impute <- function(data_incomplete_list, eta_list, lambda, rho, it_max = 10000L) {
    .Call('_changepoints_rcpp_soft_impute', PACKAGE = 'changepoints', data_incomplete_list, eta_list, lambda, rho, it_max)
}

rcpp_lambda <- function(s, e, t, alpha, rho, m, d, C_lambda) {
    .Call('_changepoints_rcpp_lambda', PACKAGE = 'changepoints', s, e, t, alpha, rho, m, d, C_lambda)
}

rcpp_CUSUM <- function(data_incomplete_list, eta_list, s, e, t, alpha, rho, m, C_lambda, delta) {
    .Call('_changepoints_rcpp_CUSUM', PACKAGE = 'changepoints', data_incomplete_list, eta_list, s, e, t, alpha, rho, m, C_lambda, delta)
}

