# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

rcpp_DP_poly <- function(y, r, gamma, delta) {
    .Call('_changepoints_rcpp_DP_poly', PACKAGE = 'changepoints', y, r, gamma, delta)
}

rcpp_DP_univar <- function(y, gamma, delta) {
    .Call('_changepoints_rcpp_DP_univar', PACKAGE = 'changepoints', y, gamma, delta)
}

rcpp_basis_poly <- function(n, s, e, r) {
    .Call('_changepoints_rcpp_basis_poly', PACKAGE = 'changepoints', n, s, e, r)
}

rcpp_hello_world <- function() {
    .Call('_changepoints_rcpp_hello_world', PACKAGE = 'changepoints')
}

